### ISSUE TITLE
Suggestions + Bugs

### ISSUE THREAD

**Issue by Chiefsam34** [SakuraSedaia/SACR-MC-Rig#1]
**{BUG}** The 2nd hat and head layer above the rig doesn't properly follow the rig in object mode, but it follows in pose mode.
**{BUG}** When switching to female mode, the rig's right leg curves inward more than the left leg.

[SUGGESTION] if there is a way you can make the extra meshes and such not be there or not be visible when appending
edit: [SUGGESTION] have a controller that ONLY rotates the feet (not ankles, like just rotating the bottoms of fancy feet while not effecting the rest of the leg, what I'm thinking of is very similar to TheButtonMash3r's mashedpotato rig's feet)

fyi I don't know much about rigging so if what I'm saying doesn't make sense or isn't possible or something, I'm sorry.

**Comment by SakuraSedaia** [comment]
I am working on an update to it now, I am implementing your suggestions into E4.2_2 now, and the way I did the legs for SACR I cannot do the final Suggestion, but I am removing the Hybrid IK system and going with a traditional one
